### ISSUE TITLE
rename repo skydive.skydive

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/skydive#4]
##### SUMMARY

Hi, can we please rename the repo to be consistent with others under gh/anisble-collections?

GitHub will maintain redirects. Once done we should review README and galaxy.yml

I assume Zuul config will also need updating

**Comment by adrianlzt** [comment]
Maybe we should rename it to ``community.skydive``?

[Doc](https://raw.githubusercontent.com/ansible-collections/overview/master/collection_requirements.rst) says:
```
We should avoid FQCN / repository names:

* which are unnecessary long: try to make it compact but clear
* contain the same words / collocations in ``NAMESPACE`` and ``COLLECTION`` parts, for example ``my_system.my_system``
```

**Comment by adrianlzt** [comment]
@gundalow do you have permissions to rename the repo and change the default branch to main (#10 )?

**Comment by gundalow** [comment]
Currently
Namespace: `skydive`
Collection: `skydive`
This is defined in https://www.github.com/ansible-collections/skydive/tree/master/galaxy.yml

**Comment by adrianlzt** [comment]
I am working on PR #11 where all has been moved to namespace ``community``
